apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: action-runner-POC
  region: eu-west-1
  tags:
    poc: action-runner-controller
managedNodeGroups:
  - name: workers
    instanceType: t3.medium
    desiredCapacity: 1
    spot: true
